/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queueJFrame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.Queue;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class queue extends javax.swing.JFrame {
    /**
     * Creates new form queue
     */
    
    Queue<Object> antrian = new LinkedList<>();
    int nomor = 0;
    
    public queue() {
        initComponents();
        inisialisasi();
        
    }
    
    private void inisialisasi(){
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            
                Date date = new Date();
                SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd             hh:mm:ss");
                txtAtas3.setText(s.format(date));
            }
        
        });
    
        timer.start();
        
        lbJmlAntrian.setText("0");
        lbTotalAntrian.setText("0");
        lbPanggilAntrian.setText("-----");
        
        //txtAtas.setText("RS USU");
        //txtAtas1.setText("Jl. Dr. Mansyur No.66, Merdeka, Kec. Medan Baru");
        //txtAtas2.setText("Kota Medan, Sumatera Utara 20154");
        
        txtAtas4.setText("Nomor Antrian");
        txtAtas5.setText("--------");
        txtAtas6.setText("Silahkan menunggu");
        txtAtas7.setText("--------");
        
    }
    
    private void tambahAntrian(){
        nomor++;
        String antr = "Antrian "+nomor;
        antrian.add(antr);
        String cvt = String.valueOf(antrian.size());
        lbJmlAntrian.setText(cvt);
        lbPanggilAntrian.setText(""+antrian.peek());
        lbTotalAntrian.setText(""+nomor);
        txtAntrian.append(antr + "\n");
        
        txtAtas4.setText("Nomor Antrian");
        txtAtas5.setText("  " + nomor);
        txtAtas6.setText("Silahkan menunggu" );
        txtAtas7.setText(lbJmlAntrian.getText() + " antrian lagi");
    }
    private void prosesAntrian(){
        if(antrian.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ambil Nomor antrian terlebih dahulu !");
        }
        txtAntrian.setText("");
        
        String jumlahAntrianString = lbJmlAntrian.getText();
        int jumlahAntrian = Integer.valueOf(jumlahAntrianString);
        if (jumlahAntrian > 0) {
            jumlahAntrian--;
        }
        
        lbJmlAntrian.setText(Integer.toString(jumlahAntrian));
        txtAtas7.setText(lbJmlAntrian.getText() + " antrian lagi");
        
        antrian.poll();
        antrian.forEach((Object element) -> {
            txtAntrian.append("" + element + "\n");
        });
        if(antrian.isEmpty()){
            lbPanggilAntrian.setText("-----");
        }else{
            lbPanggilAntrian.setText(""+antrian.peek());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lbTotalAntrian = new javax.swing.JLabel();
        lbJmlAntrian = new javax.swing.JLabel();
        lbPanggilAntrian = new javax.swing.JLabel();
        btnProsesAntrian = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtAtas4 = new javax.swing.JLabel();
        txtAtas5 = new javax.swing.JLabel();
        txtAtas6 = new javax.swing.JLabel();
        txtAtas7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAntrian = new javax.swing.JTextArea();
        btnAmbilNomorAntrian = new javax.swing.JButton();
        txtAtas3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Antrian Registrasi");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTotalAntrian.setBackground(new java.awt.Color(255, 255, 204));
        lbTotalAntrian.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTotalAntrian.setForeground(new java.awt.Color(221, 239, 250));
        lbTotalAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotalAntrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(lbTotalAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 164, 160, 55));

        lbJmlAntrian.setBackground(new java.awt.Color(255, 255, 204));
        lbJmlAntrian.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbJmlAntrian.setForeground(new java.awt.Color(221, 239, 250));
        lbJmlAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlAntrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(lbJmlAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 160, 55));

        lbPanggilAntrian.setBackground(new java.awt.Color(255, 255, 204));
        lbPanggilAntrian.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbPanggilAntrian.setForeground(new java.awt.Color(221, 239, 250));
        lbPanggilAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPanggilAntrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(lbPanggilAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 440, 160, 55));

        btnProsesAntrian.setBackground(new java.awt.Color(54, 173, 66));
        btnProsesAntrian.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnProsesAntrian.setForeground(new java.awt.Color(255, 255, 255));
        btnProsesAntrian.setText("Proses Antrian");
        btnProsesAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesAntrianActionPerformed(evt);
            }
        });
        jPanel5.add(btnProsesAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 527, 190, 118));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        txtAtas4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtAtas4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtAtas5.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txtAtas5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtAtas6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtAtas6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtAtas7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtAtas7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAtas7, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addComponent(txtAtas6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtAtas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtAtas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtAtas4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAtas5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAtas6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAtas7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 150, -1));

        txtAntrian.setEditable(false);
        txtAntrian.setBackground(new java.awt.Color(255, 255, 255));
        txtAntrian.setColumns(20);
        txtAntrian.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtAntrian.setForeground(new java.awt.Color(0, 0, 0));
        txtAntrian.setRows(5);
        jScrollPane2.setViewportView(txtAntrian);
        txtAntrian.getAccessibleContext().setAccessibleDescription("");

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 160, 340));

        btnAmbilNomorAntrian.setBackground(new java.awt.Color(254, 151, 19));
        btnAmbilNomorAntrian.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAmbilNomorAntrian.setForeground(new java.awt.Color(255, 255, 255));
        btnAmbilNomorAntrian.setText("Ambil Nomor Antrian");
        btnAmbilNomorAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbilNomorAntrianActionPerformed(evt);
            }
        });
        jPanel5.add(btnAmbilNomorAntrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 527, 190, 118));

        txtAtas3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        txtAtas3.setForeground(new java.awt.Color(255, 255, 255));
        txtAtas3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(txtAtas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 86, 184, 27));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queueJFrame/Background.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesAntrianActionPerformed
        prosesAntrian();
    }//GEN-LAST:event_btnProsesAntrianActionPerformed

    private void btnAmbilNomorAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbilNomorAntrianActionPerformed
        tambahAntrian();
    }//GEN-LAST:event_btnAmbilNomorAntrianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new queue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbilNomorAntrian;
    private javax.swing.JButton btnProsesAntrian;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbJmlAntrian;
    private javax.swing.JLabel lbPanggilAntrian;
    private javax.swing.JLabel lbTotalAntrian;
    private javax.swing.JTextArea txtAntrian;
    private javax.swing.JLabel txtAtas3;
    private javax.swing.JLabel txtAtas4;
    private javax.swing.JLabel txtAtas5;
    private javax.swing.JLabel txtAtas6;
    private javax.swing.JLabel txtAtas7;
    // End of variables declaration//GEN-END:variables
}
